name: Backend CI/CD

on:
  push:
    branches:
      - main
      - master
      - develop
      - "release/**"
      - "feature/**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
      - master
      - develop
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Run tests
        run: ./mvnw test

  build:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Build with Maven
        run: ./mvnw package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract version
        id: extract_version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          elif [[ $GITHUB_REF == refs/heads/release/* ]]; then
            VERSION=${GITHUB_REF#refs/heads/release/}-RC
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            VERSION=develop
          else
            VERSION=latest
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/system-rest:${{ steps.extract_version.outputs.VERSION }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/system-rest:latest

  deploy-dev:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://api-dev.yourdomain.com
    steps:
      - name: Deploy to development
        run: echo "Deploying backend to development environment..."

  deploy-staging:
    needs: build
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/release/'))
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://api-staging.yourdomain.com
    steps:
      - name: Deploy to staging
        run: echo "Deploying backend to staging environment..."

  deploy-production:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://api.yourdomain.com
    steps:
      - name: Deploy to production
        run: echo "Deploying backend to production environment..."
